# -*- coding: utf-8 -*-
"""Calculadora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ihwodFpCvQydgoBm4HSYXwkXPliZ2_tM
"""

while True:

  # Solicita ao usuário o primeiro número
  numero1 = float(input("Digite o primeiro número: "))
  # Solicita ao usuário o segundo número
  numero2 = float(input("Digite o segundo número: "))

  # Solicita qual operação será realizada
  operação = input("Digite a operação desejada (+, -, *, /): ")

  # Verifica se a operação escolhida foi soma
  if operação == "+":
    soma = numero1 + numero2
    print("A soma dos números é:",soma)

  # Verifica se a operação escolhida foi subtração
  elif operação == "-":
    subtracao = numero1 - numero2
    print("A subtração dos números é: ",subtracao)

  # Verifica se a operação escolhida foi multiplicação
  elif operação == "*":
    multiplicacao = numero1 * numero2
    print("A multiplicação dos números é",multiplicacao)

  # Verifica se a operação escolhida foi divisão
  elif operação =="/":
    # Impede a divisão por zero
    if numero2 == 0:
      print("Não é possível dividir por zero")
    # Se o segundo número for maior que zero a divisão será realizada
    else:
      divisao = numero1 / numero2
      print("A divisão dos números é",divisao)

  # Caso o usuário digite uma operação inválida
  else:
    print("Operação inválida!")

  # Pergunta ao usuário se ele deseja parar o programa
  parar = input("Deseja parar? (sim/não): ")

  # Se a resposta for sim, o programa é encerrado
  if parar == "sim":
   break